#!/bin/bash -ex

sudo apt-get -y install nodejs

cd git-repository

if [ ! -f config/database.yml ]; then
  cp config/database.yml.example config/database.yml
fi

bundle install --without production
bundle exec rake db:migrate
bundle exec rake test
