resources:
  - name: git-repository 
    type: git
    source:
      uri: {{app-repo-url}}
      branch: master

  - name: teroku
    type: git
    source:
      uri: https://github.com/jamiemonserrate/teroku.git
      branch: master

jobs:
  - name: test
    plan:
      - get: git-repository 
        trigger: true
      - get: teroku
      - task: test
        file: teroku/ci/test.yml
