resources:
  - name: {{app-name}}
    type: git
    source:
      uri: {{app-repo-url}}
      branch: master

  - name: teroku
    type: git
    source:
      uri: https://github.com/jamiemonserrate/teroku.git
      branch: master

jobs:
  - name: test
    plan:
      - get: {{app-name}}
      - get: teroku
      - task: test
        file: teroku/ci/test.yml
        config:
          params:
            APP_DIR: {{app-name}}
